name: semanal1
on:
  workflow_dispatch:
jobs:

  CI:
    if: github.ref == 'refs/heads/development'
    uses: ./.github/workflows/CI.yaml
    secrets: inherit

  CD_DEVELOPMENT:
    if: github.ref == 'refs/heads/development'
    needs: CI
    uses: ./.github/workflows/CD.yml
    with:
      image_name: ${{ needs.CI.outputs.image_name_development }}
    secrets: inherit

  CD_PRODUCTION:
    if: github.ref == 'refs/heads/main'
    needs: CI
    uses: ./.github/workflows/CD.yml
    with:
      image_name: ${{ needs.CI.outputs.image_name_main }}
    secrets: inherit

